name: Update readme

on:
  schedule:
    # Runs at 22:30 UTC every day
    - cron: "30 01 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    # Add permissions to allow the workflow to push changes
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          # Optional: Caching npm dependencies can speed up future runs
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate readme content
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          # The user that will author the commit
          author_name: Faham Khan
          author_email: faham@student.iul.ac.in
          
          # The commit message
          message: "docs: auto-update readme"
          
          # Add the README.md file and any SVG files
          add: "README.md *.svg"
          
          # The GITHUB_TOKEN is required to push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
